export enum GameEvents {
	LEVEL_SELECT = "LEVEL_SELECT",
	CONTROLS = "CONTROLS",
	ABOUT = "ABOUT",
	MENU = "MENU",

	LEVEL1 = "LEVEL1",
	LEVEL2 = "LEVEL2",
	LEVEL3 = "LEVEL3",
	LEVEL4 = "LEVEL4",
	LEVEL5 = "LEVEL5",
	LEVEL6 = "LEVEL6",
	LEVEL7 = "LEVEL7",
	LEVEL8 = "LEVEL8",
	LEVEL9 = "LEVEL9",


	FIRE_BALL = "FIRE_BALL",

	PLANET_COLLISION = "PLANET_COLLISION",
	PLANET_HIT_BLACKHOLE = "PLANET_HIT_BLACKHOLE",
	PLANET_OOB = "PLANET_OOB",
}

export enum GameAnimations {
	// TESTA - These will be changed later on
	CUE_IDLE = "idle",
	CUE_COLLISION = "explode",
}