export enum GameEvents {
	LEVEL_SELECT = "LEVEL_SELECT",
	CONTROLS = "CONTROLS",
	ABOUT = "ABOUT",
	MENU = "MENU",
	TRAJECTORY_SET = "TRAJECTORY_SET",
	PLAY_GAME = "PLAY_GAME",
	PAUSE = "PAUSE",
	NEXT_LEVEL = "NEXT_LEVEL",
	LEVEL_FAIL = "LEVEL_FAIL",
	LEVEL_PASS = "LEVEL_PASS",
	TRY_AGAIN = "TRY_AGAIN",

	LEVEL1 = "LEVEL1",
	LEVEL2 = "LEVEL2",
	LEVEL3 = "LEVEL3",
	LEVEL4 = "LEVEL4",
	LEVEL5 = "LEVEL5",
	LEVEL6 = "LEVEL6",
	LEVEL7 = "LEVEL7",
	LEVEL8 = "LEVEL8",
	LEVEL9 = "LEVEL9",


	FIRE_BALL = "FIRE_BALL",

	PLANET_COLLISION = "PLANET_COLLISION",
	PLANET_HIT_WORMHOLE = "PLANET_HIT_WORMHOLE",
	PLANET_HIT_BLACKHOLE = "PLANET_HIT_BLACKHOLE",
	PLANET_OOB = "PLANET_OOB",
}

export enum GameAnimations {
	// TESTA - These will be changed later on
	CUE_IDLE = "idle",
	CUE_COLLISION = "explode",
}
