export enum Homework2Event {
	PLAY_GAME = "PLAY_GAME",
	CONTROLS = "CONTROLS",
	ABOUT = "ABOUT",
	MENU = "MENU",
	FIRE_BALL = "FIRE_BALL",

	PLAYER_DAMAGE = "PLAYER_DAMAGE",
	PLAYER_I_FRAMES_END = "PLAYER_I_FRAMES_END",
	PLAYER_DEAD = "PLAYER_DEAD",
	SHIP_DAMAGE = "SHIP_DAMAGE",
	SHIP_DEAD = "SHIP_DEAD"
}

export enum Homework2Animations {
	SHIP_IDLE = "IDLE",
	SHIP_BOOST = "BOOST",
	SHIP_DIE = "DYING",
}